name: Mypy Typer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mypy

    - name: Run Mypy
      run: |
        mypy pyway/*.py
        mypy pyway/scripts/*.py
#        mypy pyway/dbms/*.py # Commented out because of errors
#        mypy pyway/tests/*.py # Commented out because of errors

